namespace: testmay22

replicaCount: 2

image:
  repository: nginx
  tag: 1.28.0
  pullPolicy: IfNotPresent

strategy:
  canary:
    steps:
      - setWeight: 20
      - pause: { duration: 30s }
      - setWeight: 20
      - pause: {}
      - setWeight: 50
      - pause: { duration: 30s }

service:
  name: argorollout-service
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
